branches:
  only:
  - master
  - develop
  - "/^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$/"
git:
  depth: 2
language: node_js
node_js:
  - "4.4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
  - "~/.meteor"
before_install:
  - if [ ! -e "$HOME/.meteor/meteor" ]; then curl https://install.meteor.com | /bin/sh; fi
install:
  - export PATH="$HOME/.meteor:$PATH"
before_script:
  - npm install
  - mkdir $HOME/app
script:
  - meteor build --architecture=os.linux.x86_64 --directory $HOME/app --server=http://localhost:3000
  - cd $HOME/app/bundle/programs/server
  - npm install --production

services:
  - mongodb
