sudo: required
dist: trusty
branches:
  only:
  - master
  - develop
  - "/^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$/"
git:
  depth: 2
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
language: node_js
node_js:
  - "4.4.7"
env:
  - CXX=g++-4.8
cache:
  directories:
    - "~/.npm"
    - "~/.meteor"
    - "node_modules"
    - "~/.meteor/local/build"
    - "~/.meteor/local/bundler-cache"
    - "~/.meteor/local/isopacks"
    - "~/.meteor/local/plugin-cache"
    - "~/nvm/versions/node/v4.4.7/bin"
    - "~/nvm/versions/node/v4.4.7/lib/node_modules"
before_install:
  - curl https://install.meteor.com | /bin/sh
  - meteor --version
  - meteor node --version
  - meteor npm --version
install:
  - export PATH="$HOME/.meteor:$PATH"
before_script:
  - meteor npm install
  - mkdir $HOME/app
script:
  - free -m
  - METEOR_PROFILE=1000 meteor build --architecture=os.linux.x86_64 --directory $HOME/app --server=http://localhost:3000
  - cd $HOME/app/bundle/programs/server
  - npm install --production

services:
  - mongodb
