language: node_js
branches:
  only:
  - master
  - develop
  - "/^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$/"
git:
  depth: 2
node_js:
  - "4.4"
cache:
  directories:
  - "~/.meteor"
before_install:
  - if [ ! -e "$HOME/.meteor/meteor" ]; then curl https://install.meteor.com | /bin/sh; fi
install:
  - export PATH="$HOME/.meteor:$PATH"
before_script:
  - npm install --production
  - mkdir $HOME/app
script:
  - meteor build --architecture=os.linux.x86_64 --directory $HOME/app --server=http://localhost:3000
  - cd $HOME/app/bundle/programs/server
  - npm install

services:
  - mongodb
