language: node_js
branches:
  only:
  - develop
  - "/^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$/"
git:
  depth: 1
node_js:
  - "0.12"
cache:
  directories:
  - "~/.meteor"
before_install:
  - if [ ! -e "$HOME/.meteor/meteor" ]; then curl https://install.meteor.com | /bin/sh; fi
install:
  - export PATH="$HOME/.meteor:$PATH"
before_script:
  - cd SONCE
  - npm install
  - mkdir /app
script:
  - meteor build --architecture=os.linux.x86_64 --directory /app --server=http://localhost:3000
services:
  - mongodb
